# Generated by Django 5.1.2 on 2025-08-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(max_length=16)),
                ('darshan_date', models.DateField()),
                ('slot', models.CharField(max_length=64)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pass_booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
