# Generated by Django 5.1.2 on 2025-08-25 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_poojabooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BhaktaNivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(max_length=16)),
                ('room_type', models.CharField(max_length=64)),
                ('ac_type', models.CharField(max_length=16)),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('member_names', models.TextField(blank=True, default='')),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_date', models.DateField()),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bhakta_nivas_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bhaktnivas',
                'ordering': ['-created_at'],
            },
        ),
    ]
