# Generated by Django 5.1.2 on 2025-08-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bhaktanivas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhaktaNivasPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.bhaktanivas')),
            ],
            options={
                'db_table': 'bhaktnivas_photo',
                'ordering': ['created_at'],
            },
        ),
    ]
