# Generated by Django 5.1.2 on 2025-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bhaktanivasphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='ac_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='booking_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='member_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='people_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='room_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bhaktanivasphoto',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
