# Generated by Django 5.1.2 on 2025-08-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bhaktanivasphoto_ac_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhaktanivasphoto',
            name='booking',
        ),
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bhaktnivas_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BhaktaNivas',
        ),
    ]
