# Generated by Django 4.2.7 on 2026-04-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr_scan', 'QR Scan'), ('face_recognition', 'Face Recognition')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('evidence_image_data', models.BinaryField(blank=True, null=True)),
                ('evidence_image_type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pooja_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='booking.poojabooking')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pooja_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pooja_verification',
                'ordering': ['-created_at'],
            },
        ),
    ]
