# Generated by Django 4.2.7 on 2026-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaktanivasphoto',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='passbooking',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
